---
- name: Installing andrewrothstein.docker_binaries for testing
  hosts: all
  roles:
    - role: andrewrothstein.docker_binaries
- name: Testing andrewrothstein.docker_cli_plugin (docker-compose)
  hosts: all
  vars:
#    docker_cli_plugin_persona: usr
    docker_cli_plugin_name: docker-compose
    docker_cli_plugin_ver: 2.26.0
    docker_cli_plugin_mirror: https://github.com/docker/compose/releases/download
    docker_cli_plugin_arch_map:
      x86_64: x86_64
    docker_cli_plugin_checksums:
      '2.26.0':
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-darwin-aarch64
        darwin-aarch64: sha256:7443f0c51d9fcb8865a5ed4cf569c2db116b7d2a4762332ca06960ca3a622e72
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-darwin-x86_64
        darwin-x86_64: sha256:90aac9e3dfd1ab57446347d6dc65ce2570d9d6165cf1b1f2185d1a6387746a45
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-aarch64
        linux-aarch64: sha256:6f00ed24a846046b441c0f0a0f8c1e00194f4b0e33f2433fac0d2dd0e486fc80
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-armv6
        linux-armv6: sha256:97dac0aa10961ea30a79f6fe2c4a13bfe4da562926365a63042fcceb88d9d125
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-armv7
        linux-armv7: sha256:d607ed69f5fe92ee1fd831cf764f977174c86192957a4de678c01db671c3dc52
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-ppc64le
        linux-ppc64le: sha256:e3afa6956f6cd4fdbaa8fe19781ae07a1bb8fb2f4d54a1aac857090d6fe1710d
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-riscv64
        linux-riscv64: sha256:1d080f5bc04b4b97c61ce3f57ff4a7bd11299f486bc287833f162360be201a7d
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-s390x
        linux-s390x: sha256:5f302fb8e7d973b53f1f9dc808d2b1af08f94687cb14b3f26cc7b358854184b5
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-x86_64
        linux-x86_64: sha256:59c6b262bedc4a02f46c8400e830e660935684899c770c3f5e804a2b7079fc16
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-windows-aarch64.exe
        windows-aarch64: sha256:faf75b42e75980e8eb0b7d5f6abcffaed444a190d86ac0223c4ab4eb809b564c
        # https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-windows-x86_64.exe
        windows-x86_64: sha256:0a9a63442f50b494e8c5b6b1af9da138d9dbbeab094e3076747a709a470bb9e9
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'docker compose version'
      ansible.builtin.command: docker compose version
      changed_when: false
      register: docker_cli_plugin_test_output
    - name: Output of 'docker compose version'
      ansible.builtin.debug:
        msg: '{{ docker_cli_plugin_test_output.stdout }}'
- name: Testing andrewrothstein.docker_cli_plugin (buildx)
  hosts: all
  vars:
#    docker_cli_plugin_persona: usr
    docker_cli_plugin_name: buildx
    docker_cli_plugin_ver: 0.12.0
    docker_cli_plugin_mirror: https://github.com/docker/buildx/releases/download
    docker_cli_plugin_arch_map:
      aarch64: arm64
      arm64: arm64
      x86_64: amd64
    docker_cli_plugin_v_dot: true
    docker_cli_plugin_checksums:
      '0.12.0':
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-amd64
        linux-amd64: sha256:7c393b92c148a0ce26c76a2abc99960be1d1097f0471978d41dc51d0c1a4471e
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-arm-v6
        linux-arm-v6: sha256:62d9162f526c3bb7f67768a5b0d81a8b3ad0371406dfc1f0775e4f62dfca7fe1
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-arm-v7
        linux-arm-v7: sha256:d941d6a5b072de775222d31d9f8467b4c1b1f56e3b08d1b78f828a9244c16464
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-arm64
        linux-arm64: sha256:781caebb36551b035cb9dcfaf91088543d09c73c4a2549341e6417d86b8bbb50
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-ppc64le
        linux-ppc64le: sha256:ab5bda4532528d6b0801c877999fce9def10c6a37624673fd13c668fdcde16b7
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-riscv64
        linux-riscv64: sha256:a2b846919c44128c6db9165ad24545e7e10035b6f0ad01559fcfbb2a13017127
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-s390x
        linux-s390x: sha256:81c2ada65624e2ac6bb4123f3a3bb933d04cfb08aa45fc55dd201ba523d96d30
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.windows-amd64.exe
        windows-amd64: sha256:dcf01329368381fae8c24b494186a30d2f1c4adb4bef7a0410b4803e5bb1c352
        # https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.windows-arm64.exe
        windows-arm64: sha256:3ace30ecc39b214f80d92c7750c5fc51510ca0eee234aa015d89929c531a22d3
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'docker buildx version'
      ansible.builtin.command: docker buildx version
      changed_when: false
      register: docker_cli_plugin_test_output
    - name: Output of 'docker buildx version'
      ansible.builtin.debug:
        msg: '{{ docker_cli_plugin_test_output.stdout }}'
